EXECUTABLE = sparse_bundle_fusion
EXTRA_SRC = CUDASolver
OBJS = build/CUDASolver/SolverBundling.o build/CUDASolver/CUDASolverBundling.o build/mLibSource.o build/main.o
SRC=../bundle_fusion_solve/src
include ../shared/make_template.inc
