EXECUTABLE = bundle_fusion_solve
EXTRA_SRC = CUDASolver
OBJS = build/CUDASolver/SolverBundling.o build/CUDASolver/CUDASolverBundling.o build/mLibSource.o build/main.o
USES_CERES=1
include ../shared/make_template.inc
